"""add_cve_cwe_tech_stack

Revision ID: c6256665f1f3
Revises: ad8d0fe1c1de
Create Date: 2026-03-20 16:50:16.433281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6256665f1f3'
down_revision: Union[str, Sequence[str], None] = 'ad8d0fe1c1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cvss_v3_score', sa.Float(), nullable=True),
    sa.Column('cvss_v3_vector', sa.String(length=200), nullable=True),
    sa.Column('cvss_v3_severity', sa.String(length=20), nullable=True),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cves_cve_id'), 'cves', ['cve_id'], unique=True)
    op.create_index(op.f('ix_cves_id'), 'cves', ['id'], unique=False)
    op.create_table('cwes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cwe_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cwes_cwe_id'), 'cwes', ['cwe_id'], unique=True)
    op.create_index(op.f('ix_cwes_id'), 'cwes', ['id'], unique=False)
    op.create_table('cve_cpes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.Integer(), nullable=False),
    sa.Column('cpe_uri', sa.String(length=500), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('product', sa.String(length=200), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cve_id'], ['cves.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cve_id', 'cpe_uri', name='uq_cve_cpe')
    )
    op.create_index(op.f('ix_cve_cpes_id'), 'cve_cpes', ['id'], unique=False)
    op.create_index(op.f('ix_cve_cpes_product'), 'cve_cpes', ['product'], unique=False)
    op.create_index(op.f('ix_cve_cpes_vendor'), 'cve_cpes', ['vendor'], unique=False)
    op.create_table('cve_cwes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.Integer(), nullable=False),
    sa.Column('cwe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_id'], ['cves.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cwe_id'], ['cwes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cve_id', 'cwe_id', name='uq_cve_cwe')
    )
    op.create_index(op.f('ix_cve_cwes_id'), 'cve_cwes', ['id'], unique=False)
    op.create_table('threat_cwes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threat_id', sa.Integer(), nullable=False),
    sa.Column('cwe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cwe_id'], ['cwes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_id'], ['threats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('threat_id', 'cwe_id', name='uq_threat_cwe')
    )
    op.create_index(op.f('ix_threat_cwes_id'), 'threat_cwes', ['id'], unique=False)
    op.create_table('technology_stacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagram_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.String(length=100), nullable=False),
    sa.Column('technology_name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('cpe_pattern', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['diagram_id'], ['diagrams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagram_id', 'element_id', 'technology_name', name='uq_diagram_element_tech')
    )
    op.create_index(op.f('ix_technology_stacks_diagram_id'), 'technology_stacks', ['diagram_id'], unique=False)
    op.create_index(op.f('ix_technology_stacks_id'), 'technology_stacks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technology_stacks_id'), table_name='technology_stacks')
    op.drop_index(op.f('ix_technology_stacks_diagram_id'), table_name='technology_stacks')
    op.drop_table('technology_stacks')
    op.drop_index(op.f('ix_threat_cwes_id'), table_name='threat_cwes')
    op.drop_table('threat_cwes')
    op.drop_index(op.f('ix_cve_cwes_id'), table_name='cve_cwes')
    op.drop_table('cve_cwes')
    op.drop_index(op.f('ix_cve_cpes_vendor'), table_name='cve_cpes')
    op.drop_index(op.f('ix_cve_cpes_product'), table_name='cve_cpes')
    op.drop_index(op.f('ix_cve_cpes_id'), table_name='cve_cpes')
    op.drop_table('cve_cpes')
    op.drop_index(op.f('ix_cwes_id'), table_name='cwes')
    op.drop_index(op.f('ix_cwes_cwe_id'), table_name='cwes')
    op.drop_table('cwes')
    op.drop_index(op.f('ix_cves_id'), table_name='cves')
    op.drop_index(op.f('ix_cves_cve_id'), table_name='cves')
    op.drop_table('cves')
    # ### end Alembic commands ###
